spring:
  application:
    name: markdown-slide
  main:
    banner-mode: off
  profiles:
    active: dev
  thymeleaf:
    cache: false
  cache:
    type: simple
    cache-names:
      - file
      - document
