spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      schema-locations:
        - classpath:/schema.sql

logging:
  level:
    root: info
    org.apache.tomcat: warn
    org.apache.catalina: warn
    org.springframework: warn
    org.hibernate: warn
    com.zaxxer.hikari: warn
