# https://github.com/marketplace/actions/github-action-for-graalvm
name: GraalVM CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up GraalVM JDK 25
        uses: graalvm/setup-graalvm@6f3fa030c4b8f77c1f554a860f593a654538fa38 # v1.5.6
        with:
          java-version: '25'
          distribution: 'graalvm-community'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - name: Build with Gradle
        run: ./gradlew --no-daemon nativeCompile
      - name: Upload binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: markdown-slide-ubuntu
          path: ./build/native/nativeCompile/markdown-slide
